import fs from 'fs/promises'
import path from 'path'
import { execa } from 'execa'
import net from 'net'
import { logger } from '../utils/logger.js'

/**
 * Port mapping for a single compose service.
 * Consumed from the "compose file parser" sibling issue.
 */
export interface ComposePortMapping {
	service: string
	hostPort: number
	containerPort: number
	protocol?: string | undefined
}

/**
 * Injected compose file utility functions.
 * These are defined as an interface so callers can inject test doubles.
 * The real implementations will come from the compose-file-parser module.
 */
export interface ComposeUtils {
	/**
	 * Parse a compose file and return all port mappings.
	 * Returns an empty array if no ports are defined.
	 */
	parseComposeFile(filePath: string): Promise<ComposePortMapping[]>

	/**
	 * Generate a compose override file that remaps host ports.
	 * Returns the absolute path to the generated override file.
	 */
	generateOverrideFile(
		mappings: ComposePortMapping[],
		identifier: string | number,
		dataDir: string
	): Promise<string>
}

/**
 * Options for foreground mode.
 */
export interface ComposeForegroundOptions {
	redirectToStderr?: boolean | undefined
	onProcessStarted?: ((pid?: number) => void) | undefined
	envOverrides?: Record<string, string> | undefined
}

/**
 * Standard compose file names to check, in order of preference.
 */
const COMPOSE_FILE_NAMES = ['compose.yml', 'compose.yaml', 'docker-compose.yml', 'docker-compose.yaml']

/**
 * Find a compose file in the given directory.
 * Checks for compose.yml, compose.yaml, docker-compose.yml, docker-compose.yaml in that order.
 * Returns the absolute path if found, null otherwise.
 */
export async function findComposeFile(worktreePath: string): Promise<string | null> {
	for (const fileName of COMPOSE_FILE_NAMES) {
		const filePath = path.join(worktreePath, fileName)
		try {
			await fs.access(filePath)
			return filePath
		} catch {
			// File doesn't exist, try the next one
		}
	}
	return null
}

/**
 * Attempt a single TCP connection to localhost:port.
 * Resolves true if the connection succeeds, false otherwise.
 * Uses a 1-second socket timeout to avoid hanging on firewalled ports.
 */
function tcpProbe(port: number): Promise<boolean> {
	return new Promise((resolve) => {
		const socket = net.createConnection({ port, host: '127.0.0.1' })
		socket.setTimeout(1000)
		const cleanup = (result: boolean): void => {
			socket.destroy()
			resolve(result)
		}
		socket.once('connect', () => cleanup(true))
		socket.once('error', () => cleanup(false))
		socket.once('timeout', () => cleanup(false))
	})
}

/**
 * ComposeDevServerStrategy handles the full docker compose lifecycle for a dev server:
 * - Stack startup (detached and foreground)
 * - Stack teardown
 * - Running status checks
 * - Port readiness detection via TCP probe
 *
 * Uses `--project-name iloom-{identifier}` to isolate compose stacks between concurrent looms.
 * Supports compose override files for port remapping (generated by the compose-file-parser module).
 */
export class ComposeDevServerStrategy {
	private readonly utils: ComposeUtils

	constructor(utils: ComposeUtils) {
		this.utils = utils
	}

	/**
	 * Build the docker compose project name for a given loom identifier.
	 * Format: `iloom-{identifier}`
	 */
	static buildProjectName(identifier: string | number): string {
		return `iloom-${identifier}`
	}

	/**
	 * Check if the compose stack is currently running.
	 * Uses `docker compose ps --quiet` and checks for running service output.
	 *
	 * @param projectName - The compose project name (iloom-{identifier})
	 * @returns true if any services are running, false otherwise
	 */
	async isStackRunning(projectName: string): Promise<boolean> {
		try {
			const result = await execa(
				'docker',
				['compose', '--project-name', projectName, 'ps', '--quiet', '--status', 'running'],
				{ reject: false }
			)
			return result.exitCode === 0 && result.stdout.trim().length > 0
		} catch {
			return false
		}
	}

	/**
	 * Start the compose stack in detached (background) mode.
	 * Applies the override file for port remapping when provided.
	 * Waits for the primary port to accept connections before returning.
	 *
	 * @param composeFile - Absolute path to the main compose file
	 * @param overrideFile - Absolute path to the generated override file (for port remapping)
	 * @param projectName - The compose project name
	 * @param envOverrides - Additional environment variables
	 */
	async startDetached(
		composeFile: string,
		overrideFile: string,
		projectName: string,
		envOverrides?: Record<string, string>
	): Promise<void> {
		const args = this.buildComposeArgs(composeFile, overrideFile, projectName)
		args.push('up', '--detach', '--wait')

		logger.info(`Starting compose stack "${projectName}" in background...`)

		const env = envOverrides
			? { ...process.env, ...envOverrides }
			: process.env

		try {
			await execa('docker', args, { env: env as NodeJS.ProcessEnv, stdio: 'inherit' })
		} catch (error) {
			const message = error instanceof Error ? error.message : 'Unknown error'
			throw new Error(`Failed to start compose stack "${projectName}": ${message}`)
		}

		logger.success(`Compose stack "${projectName}" started`)
	}

	/**
	 * Start the compose stack in foreground (blocking) mode.
	 * Returns once all services exit.
	 * Traps SIGINT/SIGTERM and forwards them to the stack via docker compose stop.
	 *
	 * @param composeFile - Absolute path to the main compose file
	 * @param overrideFile - Absolute path to the generated override file
	 * @param projectName - The compose project name
	 * @param opts - Foreground options (redirectToStderr, onProcessStarted, envOverrides)
	 */
	async startForeground(
		composeFile: string,
		overrideFile: string,
		projectName: string,
		opts: ComposeForegroundOptions = {}
	): Promise<{ pid?: number }> {
		const { redirectToStderr, onProcessStarted, envOverrides } = opts

		const args = this.buildComposeArgs(composeFile, overrideFile, projectName)
		args.push('up')

		logger.info(`Running compose stack "${projectName}" in foreground...`)

		const stdio = redirectToStderr
			? [process.stdin, process.stderr, process.stderr] as const
			: 'inherit' as const

		const env = envOverrides
			? { ...process.env, ...envOverrides }
			: process.env

		// Signal forwarding: trap SIGINT/SIGTERM and forward to the compose stack
		const forwardSignal = (): void => {
			logger.debug(`Stopping compose stack "${projectName}"`)
			void execa(
				'docker',
				[...this.buildComposeArgs(composeFile, overrideFile, projectName), 'stop'],
				{ reject: false }
			)
		}

		const onSigint = (): void => forwardSignal()
		const onSigterm = (): void => forwardSignal()

		process.on('SIGINT', onSigint)
		process.on('SIGTERM', onSigterm)

		if (onProcessStarted) {
			onProcessStarted(undefined)
		}

		try {
			await execa('docker', args, { stdio, env: env as NodeJS.ProcessEnv })
		} finally {
			process.removeListener('SIGINT', onSigint)
			process.removeListener('SIGTERM', onSigterm)
		}

		return {}
	}

	/**
	 * Stop and remove the compose stack.
	 *
	 * @param composeFile - Absolute path to the main compose file
	 * @param overrideFile - Absolute path to the override file
	 * @param projectName - The compose project name
	 * @returns true if services were stopped, false if nothing was running
	 */
	async stop(
		composeFile: string,
		overrideFile: string,
		projectName: string
	): Promise<boolean> {
		const isRunning = await this.isStackRunning(projectName)

		if (!isRunning) {
			logger.debug(`Compose stack "${projectName}" is not running`)
			return false
		}

		logger.info(`Stopping compose stack "${projectName}"...`)

		const args = this.buildComposeArgs(composeFile, overrideFile, projectName)
		args.push('down')

		try {
			await execa('docker', args, { reject: false })
		} catch (error) {
			const message = error instanceof Error ? error.message : 'Unknown error'
			throw new Error(`Failed to stop compose stack "${projectName}": ${message}`)
		}

		logger.success(`Compose stack "${projectName}" stopped`)
		return true
	}

	/**
	 * Wait for the primary port to accept TCP connections.
	 * Used for readiness detection after starting in detached mode without --wait.
	 *
	 * @param port - Host port to probe
	 * @param timeout - Maximum time to wait in milliseconds
	 * @param interval - Interval between probes in milliseconds
	 * @param projectName - Optional project name to monitor for early exit
	 * @returns true if the port accepts connections within the timeout, false otherwise
	 */
	async waitForReady(
		port: number,
		timeout: number,
		interval: number,
		projectName?: string
	): Promise<boolean> {
		const startTime = Date.now()
		let attempts = 0

		while (Date.now() - startTime < timeout) {
			attempts++

			// Early exit: if the stack has stopped, stop polling
			if (projectName && attempts % 3 === 0) {
				const stillRunning = await this.isStackRunning(projectName)
				if (!stillRunning) {
					logger.warn(
						`Compose stack "${projectName}" exited before becoming ready (after ${attempts} attempts, ${Date.now() - startTime}ms)`
					)
					return false
				}
			}

			const isReady = await tcpProbe(port)
			if (isReady) {
				return true
			}

			await new Promise<void>((resolve) => globalThis.setTimeout(resolve, interval))
		}

		return false
	}

	/**
	 * Parse the compose file and generate an override file for port remapping.
	 * Returns the host port that the primary web service will listen on.
	 *
	 * @param composeFile - Path to the main compose file
	 * @param identifier - Loom identifier (issue number, branch name)
	 * @param hostPort - Desired host port for the primary service
	 * @param dataDir - Directory where the override file will be generated
	 * @returns Path to the generated override file
	 */
	async prepareOverrideFile(
		composeFile: string,
		identifier: string | number,
		hostPort: number,
		dataDir: string
	): Promise<string> {
		const mappings = await this.utils.parseComposeFile(composeFile)

		if (mappings.length === 0) {
			throw new Error(
				`No port mappings found in compose file "${composeFile}". ` +
				'Ensure at least one service exposes a port.'
			)
		}

		// Remap the primary service's host port to the desired port
		const remapped = mappings.map((m, index) => ({
			...m,
			hostPort: index === 0 ? hostPort : m.hostPort,
		}))

		return this.utils.generateOverrideFile(remapped, identifier, dataDir)
	}

	/**
	 * Build the base docker compose args array with project name and file flags.
	 */
	private buildComposeArgs(
		composeFile: string,
		overrideFile: string,
		projectName: string
	): string[] {
		return [
			'compose',
			'--project-name', projectName,
			'-f', composeFile,
			'-f', overrideFile,
		]
	}
}
